<?php
/*
	Plugin Name: Custom User Registration Form Builder
	Plugin URI: https://wordpress.org/plugins/custom-registration-form-builder-with-submission-manager/
	Description: RegistrationMagic - Easy to use powerful WordPress Registration, SignUp and Contact Forms.
	Version: 2.5.2
	Author: CMSHelpLive
	Author URI: https://profiles.wordpress.org/cmshelplive
	License: gpl2
*/
ob_start();
/*Plugin activation hook*/
global $crf_db_version;
$crf_db_version = 3.6;
//include_once('crf_functions.php');
if (!class_exists('crf_basic_options')) {
	include 'classes/class_basic_options.php';
}
if (!class_exists('crf_basic_fields')) {
	include 'classes/class_basic_fields.php';
}
if (!class_exists('crf_paypal_class')) {
	include 'classes/paypal_class.php';
}
register_activation_hook ( __FILE__, 'activate_custom_registration_form_pro_with_sm_plugin' );
function activate_custom_registration_form_pro_with_sm_plugin()
{
	add_option('crf_db_version','3.6');
	add_option('crf_whatsnewpage',0);
	require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
	global $wpdb;
	$crf_option=$wpdb->prefix."crf_option";
	$crf_fields =$wpdb->prefix."crf_fields";
	$crf_forms =$wpdb->prefix."crf_forms";
	$crf_submissions =$wpdb->prefix."crf_submissions";
	$crf_entries =$wpdb->prefix."crf_entries";
	$crf_stats = $wpdb->prefix."crf_stats";
	$crf_paypal_fields =$wpdb->prefix."crf_paypal_fields";
	$crf_paypal_log =$wpdb->prefix."crf_paypal_log";
	$crf_notes =$wpdb->prefix."crf_notes";
	$crf_users = $wpdb->prefix . "crf_users";
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_notes (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `submission_id` int(11) NOT NULL,
	  `userid` int(11) DEFAULT NULL,
	  `useremail` varchar(255) DEFAULT NULL,
	  `type` longtext NOT NULL,
	  `status` varchar(255) DEFAULT NULL,
	  `publish_date` datetime NOT NULL,
	  `last_edit_date` datetime DEFAULT NULL,
	  `last_edited_by` varchar(255) DEFAULT NULL,
      `notes` longtext DEFAULT NULL,
	  `bg_color` varchar(255) DEFAULT NULL,
	  `extra_option` longtext DEFAULT NULL,  
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_paypal_log (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `txn_id` varchar(600) NOT NULL,
	  `log` longtext NOT NULL,
	  `posted_date` datetime NOT NULL,
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
	
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_paypal_fields (
	  `Id` int(11) NOT NULL AUTO_INCREMENT,
	  `Type` varchar(50) DEFAULT NULL,
	  `Name` varchar(256) NOT NULL,
	  `Value` longtext DEFAULT NULL,
	  `Class` varchar(256) DEFAULT NULL,
	  `Option_Label` longtext DEFAULT NULL,
	  `Option_Price` longtext DEFAULT NULL,
	  `Option_Value` longtext DEFAULT NULL,
	  `Description` longtext DEFAULT NULL,
	  `Require` varchar(256) DEFAULT NULL,
	  `Ordering` int(11) DEFAULT NULL,
	  `extra_options` longtext DEFAULT NULL,
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_stats
	(
		`id` int NOT NULL AUTO_INCREMENT,
			`form_id` int(11),
			`stats_key` varchar(255),
			`details` longtext,
			PRIMARY KEY(id)
	)";
	dbDelta( $sqlcreate );
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_option
	(
		`id` int NOT NULL AUTO_INCREMENT,
		`fieldname` varchar(255),
		`value` longtext,
		PRIMARY KEY(id)
	)";
	dbDelta( $sqlcreate );
	$insert="REPLACE INTO $crf_option VALUES
		(1, 'enable_captcha', 'no'),
		(2, 'public_key', ''),
		(3, 'private_key', ''),
		(4, 'autogeneratedepass', 'no'),
		(5, 'userautoapproval', 'yes'),
		(6, 'adminemail', ''),
		(7, 'adminnotification', 'no'),
		(8, 'from_email', ''),
		(9, 'userip', 'yes'),
		(10, 'crf_theme','default'),
		(11, 'enable_social', 'no'),
		(12, 'facebook_app_id', ''),
		(13, 'facebook_app_secret', ''),
		(14, 'enable_facebook', 'no'),
		(15, 'enable_twitter', 'no'),
		(16, 'consumer_key', ''),
		(17, 'consumer_secret', ''),
		(18, 'send_password', 'yes'),
		(19, 'enable_mailchimp', 'no'),
		(20, 'mailchimp_key', '')";
		$wpdb->query($insert);
		
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_entries
	(
		`id` int NOT NULL AUTO_INCREMENT,
		`form_id` int NOT NULL,
		`form_type` varchar(255),
		`user_approval` varchar(255),
		`value` longtext,
		 PRIMARY KEY (`id`)
	)";
	dbDelta( $sqlcreate );
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_submissions (
						`id` int(11) NOT NULL AUTO_INCREMENT,
  						`submission_id` int(11),
  						`form_id` int(11),
  						`field` text,
  						`value` longtext,
						PRIMARY KEY(id)
						)";
		dbDelta( $sqlcreate );
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_forms (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `form_name` varchar(255) DEFAULT NULL,
  `form_desc` longtext,
  `form_type` varchar(255) NOT NULL,
  `custom_text` longtext,
  `crf_welcome_email_subject` varchar(255) NOT NULL,
  `success_message` longtext,
  `crf_welcome_email_message` longtext,
  `redirect_option` varchar(255) NOT NULL,
  `redirect_page_id` int(11) NOT NULL,
  `redirect_url_url` longtext NOT NULL,
  `send_email` int(11) NOT NULL,
  `form_option` longtext,
  PRIMARY KEY (`id`)
)";
	dbDelta( $sqlcreate );
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_fields (
	  `Id` int(11) NOT NULL AUTO_INCREMENT,
	  `Form_Id` int(11) NOT NULL,
	  `Type` varchar(50) DEFAULT NULL,
	  `Name` varchar(256) NOT NULL,
	  `Value` longtext DEFAULT NULL,
	  `Class` varchar(256) DEFAULT NULL,
	  `Max_Length` varchar(256) DEFAULT NULL,
	  `Cols` varchar(256) DEFAULT NULL,
	  `Rows` varchar(256) DEFAULT NULL,
	  `Option_Value` longtext DEFAULT NULL,
	  `Description` longtext DEFAULT NULL,
	  `Require` varchar(256) DEFAULT NULL,
	  `Readonly` varchar(256) DEFAULT NULL,
	  `Visibility` varchar(256) DEFAULT NULL,
	  `Ordering` int(11) DEFAULT NULL,
	  `Field_Key` varchar(256) DEFAULT NULL,
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
/***************front end****************/
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_users (
	  `Id` int(11) NOT NULL AUTO_INCREMENT,
	  `email` varchar(255) NOT	 NULL,
	  `otp_code` varchar(255) NOT NULL,
      `last_activity_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      `created_date` timestamp, 
	  PRIMARY KEY (`Id`))";
    dbDelta($sqlcreate);
    crf_f_create_sub_page();
}
add_action( 'plugins_loaded', 'crf_update_db_check' );
function crf_update_db_check()
{
	 global $crf_db_version;
	 global $wpdb;
	 $crf_option=$wpdb->prefix."crf_option";
	 $crf_users = $wpdb->prefix . "crf_users";
	 $crf_submissions =$wpdb->prefix."crf_submissions";
	  $crf_option=$wpdb->prefix."crf_option";
	$crf_fields =$wpdb->prefix."crf_fields";
	$crf_forms =$wpdb->prefix."crf_forms";
	$crf_entries =$wpdb->prefix."crf_entries";
	
	 $save_db_version =  floatval(get_option( 'crf_db_version','1.0' ));
    if ( $save_db_version < $crf_db_version ) 
	{	
		update_option('crf_whatsnewpage',0);
		
		require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
		$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_forms (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `form_name` varchar(255) DEFAULT NULL,
  `form_desc` longtext,
  `form_type` varchar(255) NOT NULL,
  `custom_text` longtext,
  `crf_welcome_email_subject` varchar(255) NOT NULL,
  `success_message` longtext,
  `crf_welcome_email_message` longtext,
  `redirect_option` varchar(255) NOT NULL,
  `redirect_page_id` int(11) NOT NULL,
  `redirect_url_url` longtext NOT NULL,
  `send_email` int(11) NOT NULL,
  `form_option` longtext,
  PRIMARY KEY (`id`)
)";
	dbDelta( $sqlcreate );
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_fields (
	  `Id` int(11) NOT NULL AUTO_INCREMENT,
	  `Form_Id` int(11) NOT NULL,
	  `Type` varchar(50) DEFAULT NULL,
	  `Name` varchar(256) NOT NULL,
	  `Value` longtext DEFAULT NULL,
	  `Class` varchar(256) DEFAULT NULL,
	  `Max_Length` varchar(256) DEFAULT NULL,
	  `Cols` varchar(256) DEFAULT NULL,
	  `Rows` varchar(256) DEFAULT NULL,
	  `Option_Value` longtext DEFAULT NULL,
	  `Description` longtext DEFAULT NULL,
	  `Require` varchar(256) DEFAULT NULL,
	  `Readonly` varchar(256) DEFAULT NULL,
	  `Visibility` varchar(256) DEFAULT NULL,
	  `Ordering` int(11) DEFAULT NULL,
	  `Field_Key` varchar(256) DEFAULT NULL,
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_option
	(
		`id` int NOT NULL AUTO_INCREMENT,
		`fieldname` varchar(255),
		`value` longtext,
		PRIMARY KEY(id)
	)";
	dbDelta( $sqlcreate );
	$count_option = $wpdb->get_var("select count(*) from $crf_option");
	if($count_option==0)
	{
	$insert="REPLACE INTO $crf_option VALUES
		(1, 'enable_captcha', 'no'),
		(2, 'public_key', ''),
		(3, 'private_key', ''),
		(4, 'autogeneratedepass', 'no'),
		(5, 'userautoapproval', 'yes'),
		(6, 'adminemail', ''),
		(7, 'adminnotification', 'no'),
		(8, 'from_email', ''),
		(9, 'userip', 'yes'),
		(10, 'crf_theme','default'),
		(11, 'enable_social', 'no'),
		(12, 'facebook_app_id', ''),
		(13, 'facebook_app_secret', ''),
		(14, 'enable_facebook', 'no'),
		(15, 'enable_twitter', 'no'),
		(16, 'consumer_key', ''),
		(17, 'consumer_secret', ''),
		(18, 'send_password', 'yes'),
		(19, 'enable_mailchimp', 'no'),
		(20, 'mailchimp_key', '')";
		$wpdb->query($insert);
	}
	
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_entries
	(
		`id` int NOT NULL AUTO_INCREMENT,
		`form_id` int NOT NULL,
		`form_type` varchar(255),
		`user_approval` varchar(255),
		`value` longtext,
		 PRIMARY KEY (`id`)
	)";
	dbDelta( $sqlcreate );
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(6, 'adminemail', ''),
		(7, 'adminnotification', 'no')";
		$wpdb->query($insert);
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(8, 'from_email', '')";
		$wpdb->query($insert);
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(9, 'userip', 'no')";
		$wpdb->query($insert);
		
		$qry="select `value` from $crf_option where fieldname='crf_theme'";
		$crf_theme = $wpdb->get_var($qry);
		
		if(isset($crf_theme) && $crf_theme!="")
		{
			if($crf_theme=='default')
			{
				$wpdb->query("update $crf_option set value='classic' where fieldname='crf_theme'");
			}
			else
			{
				$wpdb->query("update $crf_option set value='default' where fieldname='crf_theme'");	
			}
		}
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(10, 'crf_theme', 'default')";
		$wpdb->query($insert);
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(11, 'enable_social', 'no')";
		$wpdb->query($insert);
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(12, 'facebook_app_id', '')";
		$wpdb->query($insert);
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(13, 'facebook_app_secret', '')";
		$wpdb->query($insert);
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(14, 'enable_facebook', 'no')";
		$wpdb->query($insert);
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(15, 'enable_twitter', 'no')";
		$wpdb->query($insert);
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(16, 'consumer_key', '')";
		$wpdb->query($insert);
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(17, 'consumer_secret', '')";
		$wpdb->query($insert);
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(18, 'send_password', 'yes')";
		$wpdb->query($insert);
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(19, 'enable_mailchimp', 'no')";
		$wpdb->query($insert);
		
		$insert="INSERT IGNORE INTO $crf_option VALUES
		(20, 'mailchimp_key', '')";
		$wpdb->query($insert);
		
		
		$crf_stats = $wpdb->prefix."crf_stats";
		$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_stats
		(
			`id` int NOT NULL AUTO_INCREMENT,
			`form_id` int(11),
			`stats_key` varchar(255),
			`details` longtext,
			PRIMARY KEY(id)
		)";
		dbDelta( $sqlcreate );
		$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_users (
				  		`Id` int(11) NOT NULL AUTO_INCREMENT,
				  		`email` varchar(255) NOT	 NULL,
				  		`otp_code` varchar(255) NOT NULL,
			      		`last_activity_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
			      		`created_date` timestamp, 
				  		PRIMARY KEY (`Id`))";
    	dbDelta($sqlcreate);
    	crf_f_create_sub_page();
		
		$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_submissions (
						`id` int(11) NOT NULL AUTO_INCREMENT,
  						`submission_id` int(11),
  						`form_id` int(11),
  						`field` text,
  						`value` longtext,
						PRIMARY KEY(id)
						)";
		dbDelta( $sqlcreate );
		
		$crf_paypal_fields =$wpdb->prefix."crf_paypal_fields";
		$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_paypal_fields (
		  `Id` int(11) NOT NULL AUTO_INCREMENT,
		  `Type` varchar(50) DEFAULT NULL,
		  `Name` varchar(256) NOT NULL,
		  `Value` longtext DEFAULT NULL,
		  `Class` varchar(256) DEFAULT NULL,
		  `Option_Label` longtext DEFAULT NULL,
		  `Option_Price` longtext DEFAULT NULL,
		  `Option_Value` longtext DEFAULT NULL,
		  `Description` longtext DEFAULT NULL,
		  `Require` varchar(256) DEFAULT NULL,
		  `Ordering` int(11) DEFAULT NULL,
		  `extra_options` longtext DEFAULT NULL,
		  PRIMARY KEY (`Id`))";
		dbDelta( $sqlcreate );
		
		$crf_paypal_log =$wpdb->prefix."crf_paypal_log";
	$crf_purchases =$wpdb->prefix."crf_purchases";
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_purchases (
	  `id` int(11) NOT NULL auto_increment,
	  `invoice` varchar(300) NOT NULL,
	  `trasaction_id` varchar(600) NOT NULL,
	  `log_id` int(10) NOT NULL,
	  `product_id` varchar(300) NOT NULL,
	  `product_name` varchar(300) NOT NULL,
	  `product_quantity` varchar(300) NOT NULL,
	  `product_amount` varchar(300) NOT NULL,
	  `payer_fname` varchar(300) NOT NULL,
	  `payer_lname` varchar(300) NOT NULL,
	  `payer_address` varchar(300) NOT NULL,
	  `payer_city` varchar(300) NOT NULL,
	  `payer_state` varchar(300) NOT NULL,
	  `payer_zip` varchar(300) NOT NULL,
	  `payer_country` varchar(300) NOT NULL,
	  `payer_email` text NOT NULL,
	  `payment_status` varchar(300) NOT NULL,
	  `posted_date` datetime NOT NULL,
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_paypal_log (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `txn_id` varchar(600) NOT NULL,
	  `log` longtext NOT NULL,
	  `posted_date` datetime NOT NULL,
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
	
	$crf_notes =$wpdb->prefix."crf_notes";
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $crf_notes (
	 `id` int(11) NOT NULL AUTO_INCREMENT,
	  `submission_id` int(11) NOT NULL,
	  `userid` int(11) DEFAULT NULL,
	  `useremail` varchar(255) DEFAULT NULL,
	  `type` longtext NOT NULL,
	  `status` varchar(255) DEFAULT NULL,
	  `publish_date` datetime NOT NULL,
	  `last_edit_date` datetime DEFAULT NULL,
	  `last_edited_by` varchar(255) DEFAULT NULL,
      `notes` longtext DEFAULT NULL,
	  `bg_color` varchar(255) DEFAULT NULL,
	  `extra_option` longtext DEFAULT NULL,  
	  PRIMARY KEY (`Id`))";
	dbDelta( $sqlcreate );
		
		$crf_forms =$wpdb->prefix."crf_forms";
		$crf_fields =$wpdb->prefix."crf_fields";
		$crfform = $wpdb->get_row("SELECT * FROM $crf_forms");
		//Add column if not present.
		if(!isset($crfform->form_option)){
			$wpdb->query("ALTER TABLE $crf_forms ADD form_option longtext");
		}
		
		//Add column if not present.
		if(!isset($crf_fields->Field_Key)){
			$wpdb->query("ALTER TABLE $crf_fields ADD Field_Key varchar(256) DEFAULT NULL");
			$crf_basic_options = new crf_basic_options;
			$crf_basic_options->crf_assign_key_for_previous_field();
		}
		
		$wpdb->query("ALTER TABLE $crf_forms CHANGE `success_message` `success_message` LONGTEXT");
		$wpdb->query("ALTER TABLE $crf_paypal_fields CHANGE `Option_Label` `Option_Label` LONGTEXT");
		$wpdb->query("ALTER TABLE $crf_paypal_fields CHANGE `Option_Price` `Option_Price` LONGTEXT");
		$wpdb->query("ALTER TABLE $crf_paypal_fields CHANGE `Option_Value` `Option_Value` LONGTEXT");
		$wpdb->query("ALTER TABLE $crf_fields CHANGE `Option_Value` `Option_Value` LONGTEXT");
		
		$submissions = get_option( 'crf_migrate_submission','no' );
		if($submissions=='no')
		{
			update_option( "crf_db_version", $crf_db_version );
			wp_redirect('admin.php?page=crf_migrate_submission');exit;
		}
		else
		{
			update_option( "crf_db_version", $crf_db_version );	
		}
		
		
		
	}
	$whatsnew = get_option( 'crf_whatsnewpage',0 );
	if($whatsnew ==0)
	{
		update_option('crf_whatsnewpage',1);
		wp_redirect('admin.php?page=crf_whats_new');exit;
	}
}
add_action( 'admin_notices', 'crf_admin_notice' );
function crf_admin_notice() 
{
	global $wpdb;
	$textdomain = 'custom-registration-form-builder-with-submission-manager';
	$submissions = get_option( 'crf_migrate_submission','no' );
		if($submissions=='no')
		{
			$crf_entries =$wpdb->prefix."crf_entries";
			$crfform = $wpdb->get_var("SELECT count(*) FROM $crf_entries ");
			if(isset($crfform) && $crfform!=0){
			?>
			<div class="updated">
				<p><?php _e( 'Your Custom Registration form builder has old version content. You will need to <a href="admin.php?page=crf_migrate_submission"> upgrade</a>', $textdomain ); ?></p>
			</div>
			<?php
			}
		}
}
add_action( 'init', 'crf_load_textdomain' );
function crf_load_textdomain() {
  load_plugin_textdomain( 'custom-registration-form-builder-with-submission-manager', false, plugin_basename( dirname( __FILE__ ) ) . '/languages' ); 
}
add_action( 'wp_enqueue_scripts', 'crf_frontend_script' );
add_action( 'admin_init', 'crf_admin_script' );
/*Defines enqueue style/ script for front end*/
function crf_frontend_script() {
	//wp_enqueue_style( 'crf-style.css', plugin_dir_url(__FILE__) . 'css/crf-style.css');
	global $wpdb;
	$lang = get_option('crf_recaptcha_lang','en');
	$crf_option=$wpdb->prefix."crf_option";
	$qry="select `value` from $crf_option where fieldname='crf_theme'";
	$crf_theme = $wpdb->get_var($qry);
	wp_enqueue_style( 'crf-style-'.$crf_theme, plugin_dir_url(__FILE__) . 'css/crf-style-'.$crf_theme.'.css');
	wp_enqueue_script( 'jquery' );
	wp_enqueue_script( 'tcal.js', plugin_dir_url(__FILE__) . 'js/tcal.js');
	wp_enqueue_style('tcal.css',plugin_dir_url(__FILE__) . 'css/tcal.css');
	wp_enqueue_script("crf-recaptcha-api","https://www.google.com/recaptcha/api.js?hl=$lang");
	/*****************front end******************************/
       /*Front end style*/
    wp_enqueue_style( 'crf_front.css', plugin_dir_url(__FILE__) . 'css/crf_front.css');
    /* Front end script */
    wp_enqueue_script('cfr_front.js', plugin_dir_url(__FILE__) . 'js/crf_front.js');
}
/*Defines enqueue style/ script for dashboard*/
function crf_admin_script() {
	wp_enqueue_style( 'crf-user.css', plugin_dir_url(__FILE__) . 'css/crf-user.css');
	wp_enqueue_style( 'crf-usermanager.css', plugin_dir_url(__FILE__) . 'css/crf-usermanager.css');
	wp_enqueue_script( 'tcal.js', plugin_dir_url(__FILE__) . 'js/tcal.js');
	wp_enqueue_style('tcal.css',plugin_dir_url(__FILE__) . 'css/tcal.css');
	wp_enqueue_style( 'crf-admin.css', plugin_dir_url(__FILE__) . 'css/crf-admin.css');
	wp_enqueue_script( 'jquery' );
	wp_enqueue_Script('jquery-ui-dialog');
	wp_enqueue_Script('jquery-ui-sortable');
	wp_register_style('crf_googleFonts', 'http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700');
    wp_enqueue_style( 'crf_googleFonts');
	wp_enqueue_script( 'ZeroClipboard.js',  plugin_dir_url(__FILE__) . 'js/ZeroClipboard.js');	
	wp_enqueue_script( 'jquery-ui-tooltip');	
	wp_enqueue_style( 'crf_analytics', plugin_dir_url(__FILE__) . 'css/crf_analytics.css');
	wp_enqueue_script( 'crf_admin.js', plugin_dir_url(__FILE__) . 'js/admin.js','','',true);
	wp_enqueue_script( 'crf_jsapi', 'https://www.google.com/jsapi');
	wp_enqueue_style( 'wp-color-picker' );
	wp_enqueue_script( 'wp-color-picker' );
	wp_enqueue_script( 'jQuery UI Effects' );
	wp_enqueue_script( 'jquery-effects-blind' );
	wp_enqueue_script( 'jquery-ui-tabs' );
}
/*Defines menu and sub-menu items in dashboard*/
add_action('admin_menu', 'custom_registration_form_pro_with_sm_menu');
function custom_registration_form_pro_with_sm_menu()
{
	add_menu_page("Registrations","Registrations","manage_options","crf_manage_forms","crf_manage_forms",plugins_url('/images/profile-icon2.png', __FILE__),"28.01");
	add_submenu_page("crf_manage_forms","New Form","New Form","manage_options","crf_add_form","crf_add_form");
	add_submenu_page("crf_manage_forms","Global Settings","Global Settings","manage_options","crf_settings","crf_settings");
	
	add_submenu_page("","General Settings","General Settings","manage_options","crf_general_settings","crf_general_settings");
	add_submenu_page("","Anti Spam Settings","Anti Spam Settings","manage_options","crf_antispam_settings","crf_antispam_settings");
	add_submenu_page("","User Account Settings","User Account Settings","manage_options","crf_user_settings","crf_user_settings");
	add_submenu_page("","Auto Responder Settings","Auto Responder Settings","manage_options","crf_autoresponder_settings","crf_autoresponder_settings");
	add_submenu_page("","Third Party Integration Settings","Third Party Integration Settings","manage_options","crf_thirdparty_settings","crf_thirdparty_settings");
	add_submenu_page("","Payment Settings","Payment Settings","manage_options","crf_payment_settings","crf_payment_settings");
	add_submenu_page("crf_manage_forms","Submissions","Submissions","manage_options","crf_entries","crf_entries");
	add_submenu_page("","Manage Form Fields","Manage Form Fields","manage_options","crf_manage_form_fields","crf_manage_form_fields");
	add_submenu_page("","View Entry","View Entry","manage_options","crf_view_entry","crf_view_entry");
	add_submenu_page("","Migrate Submission","Migrate Submission","manage_options","crf_migrate_submission","crf_migrate_submission");
	add_submenu_page("","Add Field","Add Field","manage_options","crf_add_field","crf_add_field");
	add_submenu_page("crf_manage_forms","Form Analytics","Form Analytics","manage_options","crf_stats","crf_stat");
	add_submenu_page("crf_manage_forms","Field Analytics demo","Field Analytics demo","manage_options","analytics_demo","analytics_demo");
	add_submenu_page("","Whats New","Whats New","manage_options","crf_whats_new","crf_whats_new");
	add_submenu_page("crf_manage_forms","Price Fields","Price Fields","manage_options","crf_manage_paypal_fields","crf_manage_paypal_fields");
	add_submenu_page("","Add Paypal Field","Add Paypal Field","manage_options","crf_add_paypal_field","crf_add_paypal_field");
	add_submenu_page("crf_manage_forms","Attachments","Attachments","manage_options","crf_manage_attachments","crf_manage_attachments");
	add_submenu_page("crf_manage_forms","User Roles","User Roles","manage_options","crf_user_role","crf_user_role");
	add_submenu_page("crf_manage_forms","Users","Users","manage_options","crf_user_manager","crf_user_manager");
	add_submenu_page("","User","User","manage_options","crf_view_wp_user","crf_view_wp_user");
	add_submenu_page("","Edit User","Edit User","manage_options","crf_edit_wp_user","crf_edit_wp_user");
	add_submenu_page("crf_manage_forms","Support","Support","manage_options","crf_support","crf_support");
}

function crf_edit_wp_user()
{
	include 'crf_edit_user.php';	
}

function crf_view_wp_user()
{
	include 'crf_single_user.php';		
}

function crf_user_manager()
{
	include 'user_manager.php';	
}

function crf_user_role()
{
	include 'user_role.php';	
}


function crf_manage_paypal_fields()
{
	include 'paypal_fields_manager.php';	
}

function crf_manage_attachments()
{
	include 'manage_attachments.php';
}

function crf_payment_settings()
{
	include 'payment_settings.php';	
}
function crf_add_paypal_field()
{
	include 'add_paypal_field.php';
}
function crf_whats_new()
{
	include 'whats_new.php';	
}
function crf_thirdparty_settings()
{
	include 'third_party_integration_settings.php';	
}
function crf_general_settings()
{
	include 'general_settings.php';	
}
function crf_antispam_settings()
{
	include 'anti_spam_settings.php';	
}
function crf_user_settings()
{
	include 'user_account_settings.php';	
}
function crf_autoresponder_settings()
{
	include 'auto_responder_settings.php';	
}
function crf_migrate_submission()
{
	include('crf_migrate_submission.php');
}
function crf_stat()
{
	include 'stats.php';	
}

function analytics_demo()
{
	include 'crf_analytics.php';	
}

function add_crf_menu_adminbar() {
	global $wp_admin_bar;
	$wp_admin_bar->add_menu( array(
		'id'    => 'crf_add_form',
		'title' => 'Form',
		'href'  => admin_url().'admin.php?page=crf_add_form',
		'parent'=>'new-content'
	));
}
add_action( 'wp_before_admin_bar_render', 'add_crf_menu_adminbar' ); 
function crf_settings()
{
	//include 'crfoption.php';
	include 'settings.php';
}
function crf_support()
{
	include 'crf_support.php';	
}
function crf_add_form()
{
	include 'add-form.php';	
}
function crf_add_field()
{
	include 'add_field.php';
}
function crf_view_entry()
{
	include 'view_entry.php';	
}
function crf_manage_forms()
{
	include 'manage-form.php';
}
function crf_entries()
{
	include 'manage_entries.php';
}
function crf_manage_form_fields()
{
	include 'manage-form-fields.php';
}

add_shortcode( 'CRF_Form', 'CRF_view_form_fun' );
function CRF_view_form_fun($content)
{
	ob_start();
/*	global $wpdb;
	$crf_option=$wpdb->prefix."crf_option";
	$qry="select `value` from $crf_option where fieldname='crf_theme'";
	$crf_theme = $wpdb->get_var($qry);
	include 'view-form-'.$crf_theme.'.php';*/
	include 'view-form-default.php';
	$output_string=ob_get_contents();
	ob_end_clean();
	return $output_string;
}
add_shortcode( 'CRF_Login', 'CRF_view_login_form_fun' );
function CRF_view_login_form_fun($content)
{
	ob_start();
	include 'crf_login.php';
	$output_string=ob_get_contents();
	ob_end_clean();
	return $output_string;
}
add_action('wp_ajax_set_field_order', 'CRF_set_field_order');
add_action('wp_ajax_nopriv_set_field_order', 'CRF_set_field_order');
function CRF_set_field_order()
{
	global $wpdb;
	include('set_field_order.php');die;
}
add_action('wp_ajax_crf_ajaxcalls', 'CRF_ajaxcalls');
add_action('wp_ajax_nopriv_crf_ajaxcalls', 'CRF_ajaxcalls');
function CRF_ajaxcalls()
{
	global $wpdb;
	include('crf_ajaxCalls.php');
	die;
}
add_action('wp_ajax_check_crf_field_name', 'CRF_check_field_name');
add_action('wp_ajax_nopriv_check_crf_field_name', 'CRF_check_field_name');
function CRF_check_field_name()
{
	global $wpdb;
	include('check_crf_field_name.php');
	die;
}
add_action('wp_ajax_check_crf_form_name', 'CRF_check_form_name');
add_action('wp_ajax_nopriv_check_crf_form_name', 'CRF_check_form_name');
function CRF_check_form_name()
{
	global $wpdb;
	include('check_crf_form_name.php');
	die;
}
add_action('wp_ajax_crf_add_ajax_form', 'CRF_add_ajax_form');
add_action('wp_ajax_nopriv_crf_add_ajax_form', 'CRF_add_ajax_form');
function CRF_add_ajax_form()
{
	global $wpdb;
	include('add_ajax_form.php');
	die;
}
add_action('wp_ajax_crf_start_migrate_submission', 'CRF_start_migrate_submission');
add_action('wp_ajax_nopriv_crf_start_migrate_submission', 'CRF_start_migrate_submission');
function CRF_start_migrate_submission()
{
	global $wpdb;
	include('crf_migration_process.php');
	die;
}
add_action('wp_ajax_check_crf_paypal_field_name', 'CRF_check_paypal_field_name');
add_action('wp_ajax_nopriv_check_crf_paypal_field_name', 'CRF_check_paypal_field_name');
function CRF_check_paypal_field_name()
{
	global $wpdb;
	include('check_paypal_field.php');
	die;
}
add_action('wp_ajax_set_paypal_field_order', 'CRF_set_paypal_field_order');
add_action('wp_ajax_nopriv_set_paypal_field_order', 'CRF_set_paypal_field_order');
function CRF_set_paypal_field_order()
{
	global $wpdb;
	include('set_paypal_field_order.php');die;
}
add_action('wp_ajax_crf_pdf_download', 'CRF_pdf_download');
add_action('wp_ajax_nopriv_crf_pdf_download', 'CRF_pdf_download');
function CRF_pdf_download()
{
	global $wpdb;
	//echo 'test';die;
	include('pdfdownload.php');die;
}
add_action('media_buttons','add_new_form_editor_button',15.1);
function add_new_form_editor_button()
{
	 $screen = get_current_screen();
	if($screen->base=='post')
	{
	include 'add_shortcode_button.php';
	}
	
}
add_filter( 'register_url', 'crf_custom_register_url' );
function crf_custom_register_url($default_registration_url)
{
	 $default_registration_url = get_option('ucf_default_Registration_url',0);
	 if($default_registration_url==0)
	 {
		$register_url = site_url('/wp-login.php?action=register'); 
	 }
	 else
	 {
  	 	$register_url = get_permalink($default_registration_url);
	 }
    return $register_url;
}

// Function that outputs the contents of the dashboard widget
function crf_dashboard_widget_function( $post, $callback_args ) {
	$form_fields = new crf_basic_fields;
	$startdate = mktime(0, 0, 0, date("m")  , date("d"), date("Y"));
	$enddate =  time();
	$submissions = $form_fields->crf_get_submissions_latest_submission();	
	$form_fields->crf_get_short_submissions($submissions);
}
// Function used in the action hook
function crf_add_dashboard_widgets() {
	wp_add_dashboard_widget('dashboard_widget', 'Latest Submissions', 'crf_dashboard_widget_function');
}
// Register the new dashboard widget with the 'wp_dashboard_setup' action
add_action('wp_dashboard_setup', 'crf_add_dashboard_widgets' );
add_filter( 'widget_text', 'shortcode_unautop');
add_filter( 'widget_text', 'do_shortcode');


add_filter( 'plugin_action_links_' . plugin_basename(__FILE__), 'crf_plugin_action_links' );

function crf_plugin_action_links( $links ) {
   $links[] = '<a href="'. esc_url( get_admin_url(null, 'admin.php?page=crf_settings') ) .'">Settings</a>';
   $links[] = '<a href="http://registrationmagic.com/knowledgebase/" target="_blank">Documentation</a>';
   return $links;
}

function crf_user_last_login( $user_login, $user ){
	// Get user meta
		$disabled = get_user_meta( $user->ID, 'crf_user_status', true );
		
		// Is the use logging in disabled?
		if ( $disabled == 'deactivate' ) 
		{
			// Clear cookies, a.k.a log user out
			 wp_clear_auth_cookie();
			// Build login URL and then redirect
			$login_url = site_url( 'wp-login.php', 'login' );
			$login_url = add_query_arg( 'disabled', '1', $login_url );
			wp_redirect( $login_url );
			exit;
		}
		
    update_user_meta( $user->ID, 'crf_last_login', time() );
}

function crf_user_login_message( $message ) {
	$textdomain = 'custom-registration-form-builder-with-submission-manager';
		// Show the error message if it seems to be a disabled user
		if ( isset( $_GET['disabled'] ) && $_GET['disabled'] == 1 ) 
			$message =  '<div id="login_error">' . __( 'Account disabled',$textdomain) . '</div>';
		return $message;
	}
	
add_filter( 'login_message', 'crf_user_login_message');

add_action( 'wp_login', 'crf_user_last_login', 10, 2 );

/***********************Front end added here************************************/
/* Front end code */
add_shortcode('CRF_Submissions', 'CRF_view_submissions');
function CRF_view_submissions()
{
    if (!Front_Utility::is_authorized()) {
        _e('You are not authorized to access the submissions.', 'textdomain');
    } else {
        if ($_POST){
        	include("view_submission_details.php");
        	
        }
        else{
			include('view_submissions.php');
        }
            
    }
}
/* OTP widget */
include_once("classes/class_otp_widget.php");
include_once("classes/class_front_utility.php");
include('generatepdf.php');
add_action('widgets_init', function () {
    register_widget('OTP_Widget');
});
add_action('wp_ajax_nopriv_crf_set_otp', 'CRF_set_otp');
function CRF_set_otp()
{
    Front_Utility::set_otp();
}
add_action('init', 'crf_del_otp');
function crf_del_otp()
{
    Front_Utility::cron();
}
//ajax request for store comments to the database
add_action('wp_ajax_nopriv_crf_store_comment','crf_store_comment');
add_action('wp_ajax_crf_store_comment','crf_store_comment');
//function to store comments in database
function crf_store_comment(){
    Front_Utility::crf_store_comment();
}
//ajax request for store attatchment to the database
add_action('wp_ajax_nopriv_store_crf_attatchment','store_crf_attatchment');
add_action('wp_ajax_store_crf_attatchment','store_crf_attatchment');
//function to store attatchments in database
function store_crf_attatchment(){
    Front_Utility::store_crf_attatchment();
}
add_action('wp_ajax_nopriv_upload_crf_image','upload_crf_image');
add_action('wp_ajax_upload_crf_image','upload_crf_image');
//function to upload image to database
function upload_crf_image(){
    Front_Utility::upload_crf_image();
}
add_action('wp_ajax_nopriv_delete_comment_f','delete_comment_f');
add_action('wp_ajax_delete_comment_f','delete_comment_f');
//deletes a comment on crf front submission page 
function delete_comment_f(){
    Front_Utility::delete_comment_f();
}
add_action('wp_ajax_nopriv_crf_f_logout','crf_f_logout');
//logout functionality for front end 
function crf_f_logout(){
    Front_Utility::logout();
    die;
}
//creates a new page to view submissions on front end
function crf_f_create_sub_page(){
	Front_Utility::create_page();
}
?>