<?php
/*Controls custom field creation in the dashboard area*/
global $wpdb;
$textdomain = 'custom-registration-form-builder-with-submission-manager';
$crf_option=$wpdb->prefix."crf_option";
$path =  plugin_dir_url(__FILE__); 
$useraccount_options = new crf_basic_options;
if(isset($_REQUEST['saveoption']))
{
	$retrieved_nonce = $_REQUEST['_wpnonce'];
	if (!wp_verify_nonce($retrieved_nonce, 'save_crf_user_account_setting' ) ) die( 'Failed security check' );
	if(!isset($_REQUEST['send_password'])) $_REQUEST['send_password']='no';
	if(!isset($_REQUEST['autogenerate_pass'])) $_REQUEST['autogenerate_pass']='no';
	$useraccount_options->crf_add_option( 'autogeneratedepass', $_REQUEST['autogenerate_pass']);
	if($_REQUEST['autogenerate_pass']=='yes')
	{
		$useraccount_options->crf_add_option( 'send_password','yes');	
	}
	else
	{
		$useraccount_options->crf_add_option( 'send_password', $_REQUEST['send_password']);
	}
	wp_redirect('admin.php?page=crf_settings');exit;
}
?>
<div class="crf-main-form">
  <div class="crf-form-heading">
    <h1><?php _e( 'User Accounts', $textdomain ); ?></h1>
  </div>
  <form method="post">
    
    <div class="option-main crf-form-setting">
      <div class="user-group crf-form-left-area">
        <div class="crf-label">
          <?php _e( 'Auto Generated Password:', $textdomain ); ?>
        </div>
      </div>
      <div class="user-group-option crf-form-right-area">
        <input name="autogenerate_pass" id="autogenerate_pass" type="checkbox" class="upb_toggle" value="yes" <?php if ($useraccount_options->checkfieldname("autogeneratedepass","yes")==true){ echo "checked";}?> style="display:none;" />
        <label for="autogenerate_pass"></label>
      </div>
    </div>
    
    <div class="option-main crf-form-setting sendpasswordoption" <?php if($useraccount_options->checkfieldname("autogeneratedepass","yes")==true){ echo 'style="display:none"';}else{echo 'style="display:block"';}?>>
      <div class="user-group crf-form-left-area">
        <div class="crf-label">
          <?php _e( 'Send Username and Password To User Through Email:', $textdomain ); ?>
        </div>
      </div>
      <div class="user-group-option crf-form-right-area">
        <input name="send_password" id="send_password" type="checkbox" class="upb_toggle" value="yes" <?php if ($useraccount_options->checkfieldname("send_password","yes")==true){ echo "checked";}?> style="display:none;"/>
        <label for="send_password"></label>
      </div>
    </div>
    
    <div class="option-main crf-form-setting crf_lock_feature">
      <div class="user-group crf-form-left-area">
        <div class="crf-label">
          <?php _e( 'WP Registration Auto Approval:', $textdomain ); ?>
        </div>
      </div>
      <div class="user-group-option crf-form-right-area">
        <input name="user_auto_approval" id="user_auto_approval" type="checkbox" class="upb_toggle" value="yes" style="display:none;" checked disabled/>
        <label for="user_auto_approval"></label>
        <span class="crf_pro_features"><?php _e('Only Available in Pro Editions.',$textdomain);?> <a href="http://registrationmagic.com/?download_id=317&edd_action=add_to_cart"><?php _e('Click here',$textdomain);?></a><?php _e(' to upgrade.',$textdomain);?></span>
      </div>
    </div>
    
    
    
    <br>
    <br>
    <div class="crf-form-footer">
      <div class="crf-form-button">
      <?php wp_nonce_field('save_crf_user_account_setting'); ?>
        <input type="submit"  class="button-primary" value="<?php _e('Save',$textdomain);?>" name="saveoption" id="saveoption" />
        <a href="admin.php?page=crf_settings" class="cancel_button"><?php _e('Cancel',$textdomain);?></a>
      </div>
    </div>
  </form>
</div>